export type Stats = {
  str: number;
  dex: number;
  con: number;
  int: number;
  wis: number;
  cha: number;
  maxHP: number;
  hp: number;
  maxMana: number;
  mana: number;
  ac: number;
};

export type IPlayerStats = {
  toSave: () => Stats;
  setStr: (hp: number) => void;
  setDex: (hp: number) => void;
  setCon: (hp: number) => void;
  setInt: (hp: number) => void;
  setWis: (hp: number) => void;
  setCha: (hp: number) => void;
  setMaxMana: (mana: number) => void;
  setMaxHP: (hp: number) => void;
  setMana: (mana: number) => void;
  setHP: (hp: number) => void;
  setAC: (ac: number) => void;
  getAttributes: () => any;
  getMaxHP: () => number;
  getMaxMana: () => number;
  getMana: () => number;
  getHP: () => number;
  getAC: () => number;
  changeStr: (changeValue: number) => void;
  changeDex: (changeValue: number) => void;
  changeCon: (changeValue: number) => void;
  changeInt: (changeValue: number) => void;
  changeWis: (changeValue: number) => void;
  changeCha: (changeValue: number) => void;
  changeMaxMana: (changeValue: number) => void;
  changeMaxHP: (changeValue: number) => void;
  changeMana: (changeValue: number) => void;
  changeHP: (changeValue: number) => void;
  changeAC: (changeValue: number) => void;
  _equalizeToMaxMana: () => void;
  _equalizeToMaxHP: () => void;
};
