name: Deploy Zork to GH Pages

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/setup-node@v3

      - name: Setup Node
        uses: action/setup-node@v3
        with:
          node-version: "16"
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run predeploy

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    environment:
      name: gh-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
