name: Deploy Zork to GH Pages

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/setup-node@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        working-directory: ./
        run: npm i

      - name: Build
        run: npm run predeploy

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    environment:
      name: gh-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
